name: treepedia
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - gdal
  - pyproj
  - fiona
  - pillow
  - shapely
  - matplotlib
  - xmltodict
  - numpy
  - isort
  - autoflake
  - pre-commit
  - black
  - flake8
  - tqdm
  - folium
  - geopandas
  - jupyterlab
  - pre-commit
  - scikit-image
  - osmnx
  - seaborn
  - aiohttp
